export default {
  HOME: 'HOME',
  EXTRA: 'Extra',
  CATEGORIES: 'CATEGORIES',
  CATEGORY_POSTS: 'CATEGORY_POSTS',
  POSTS: 'POSTS',
  BOOKMARKS: 'BOOKMARKS',
  SETTINGS: 'SETTINGS',
  TERMS_CONDITIONS: 'TERMS_CONDITIONS',
  PRIVACY_POLICY: 'PRIVACY_POLICY',
  NOTIFICATIONS: 'NOTIFICATIONS',
};
