export default {
  HOME: 'HOME',
  EXTRA: 'Extra',
  CATEGORIES: 'CATEGORIES',
  CATEGORY_POSTS: 'CATEGORY_POSTS',
  POSTS: 'POSTS',
  BOOKMARKS: 'BOOKMARKS',
  SETTINGS: 'SETTINGS',
  NOTIFICATIONS: 'NOTIFICATIONS',
  SEARCH: 'SEARCH',
  COMMENTS: 'COMMENTS',
  WEB: 'WEB',
};
